name = "NVMagnetometer"
uuid = "28fc4bcf-da03-4841-bbdb-88baaf311b30"
authors = ["Huaiming Yu<huaimingyuuu@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuanEstimationBase = "9769ca81-ed10-4016-bab9-e66dc61d4d60"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0"
QuanEstimationBase = "0.1"
julia = "1.10"
